### ISSUE TITLE
Question：What should fill in the objective_ids

### ISSUE THREAD

**Issue by Euraxluo** [UMich-BipedLab/IMOMD-RRTStar#1]
```yaml
#  ## Seattle
#  source_id: 486234
#  objective_ids: [433402, 426716, 617432, 887981, 469267,
#                  660438, 271555, 209507, 814027, 538265,
#                  112753, 398120, 623085, 782523, 289206,
#                  377816, 367108, 401203, 725126, 870459,
#                  323008, 525033, 594246]
#  target_id: 683162
```
The id is what mean，the osm XML file like:
```xml
<node id="62523898" visible="true" version="3" changeset="14066369" timestamp="2012-11-27T23:43:00Z" user="techlady" uid="104962" lat="42.2939547" lon="-83.7189858"/>
 <node id="62523900" visible="true" version="3" changeset="14060680" timestamp="2012-11-27T16:56:41Z" user="techlady" uid="104962" lat="42.2939785" lon="-83.7101374"/>
 <node id="62523903" visible="true" version="3" changeset="14060680" timestamp="2012-11-27T16:56:41Z" user="techlady" uid="104962" lat="42.2940563" lon="-83.7096656"/>
 <node id="62523905" visible="true" version="3" changeset="14060680" timestamp="2012-11-27T16:56:41Z" user="techlady" uid="104962" lat="42.2941456" lon="-83.7094430"/>
 <node id="62523907" visible="true" version="3" changeset="14060680" timestamp="2012-11-27T16:56:41Z" user="techlady" uid="104962" lat="42.2943013" lon="-83.7091244"/>
 
```
The id is the id of the node?

**Comment by Euraxluo** [comment]
It's done，objective_ids is index of the node load order

**Comment by gokcesena** [comment]
I don't understand, for example if we want to update the objective_id location for sanf.osm file, what numbers do I have to look at?

**Comment by dom-lee** [comment]
@gokcesena, thank you for your interest in our package!

We've also noticed the issue you pointed out and have made a fix. We've updated the package to directly use the id from the OSM XML file in the configuration file.

However, before we publish the updated version, you can make a minor adjustment to your code to get around this problem. You can add a getter function to get an index of a node corresponding to the node id from the OSM XML file by using the `nodes_id_idx_table_` variable [here](https://github.com/UMich-BipedLab/IMOMD-RRTStar/blob/4a4a3bda2b5e57c82d4eb7b7602b9f8eff0d5091/include/osm_converter/osm_parser.h#L92).

Moreover, you'll also need to convert the OSM id from the configuration file into an index of loaded nodes in the `main.cpp` [here](https://github.com/UMich-BipedLab/IMOMD-RRTStar/blob/4a4a3bda2b5e57c82d4eb7b7602b9f8eff0d5091/include/osm_converter/osm_parser.h#L92).

Alternatively, you can use our ROS wrapper version which allows you to get the index simply by clicking on the node in RViz. We hope this helps you for now, and please stay tuned for the updated version of the package!

**Comment by Euraxluo** [comment]
I'm going to re-implement the paper, use rust, and provide interoperability with Python.
https://github.com/Euraxluo/IMOMD-RRTStar-rs
